install.packages(c("quantmod","corrplot")) 
library(quantmod) 
library(corrplot)
rates=c("USD/EUR","USD/GBP","USD/CHF","USD/JPY",  "USD/CAD","USD/AUD","USD/IDR") 
getSymbols(rates,src="oanda", return.class = 'data.frame') 
fxdata = cbind(USDAUD,USDCAD,USDCHF,USDEUR,USDGBP,USDIDR,USDJPY) 
fxcor = cor(fxdata)

par(mfrow=c(2,2)) 
corrplot(fxcor, method = c("ellipse")) 
corrplot(fxcor, method = c("number")) 
corrplot(fxcor, method = c("square")) 
corrplot(fxcor, method = c("square"), type = "lower") 
corrplot(fxcor, method = c("number"),order="hclust", addrect = 4, rect.col="blue")